# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90c10f06c5ee4f303834fce3aef971a5b38d31b4d70cc2a6f5e91ed2853a1a5d9b686c59946d0391ada7091f1a2a06c7135b289c618f3ab113a22f8b23a59b43

test:
  secret_key_base: 4242ad8b1cb6a647cb427f3fa14d326e42ba54fdd06cec99fdbd1241e39c6850ed473971a3d3d9472d2a956bbd60b100323dd269cf098c2316fcf4eb466d346e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
